### ISSUE TITLE
N@TM Planning 

### ISSUE THREAD

**Issue by Nope1013** [sommerss/RobertAllen-Male-#5]
### N@TM Project
---
### Part 1- Online reading log
**Project Purpose:** Our project will serve as a sort of online reading log, to allow users to keep track of their reading in an increasingly digital world. The user will be able to input their user ID, their name, the date, the name of the book, and their rating of the book, and receive an accurate log to keep track of their reading.
### Part 2- Game with leader board
**Project Purpose:** The purpose of this game is to increase observational skills by having players locate the different colored circle within the grid. It will also include a leaderboard, which will use a binary search algorithm to sort players based on their score and display the top ten players.
### Incorporation: 
Our project is a site for children to motivate them to read. After a certain amount of pages, the users can unlock different levels in the game.
- [x] team members: Shreya (scrum master), Noor (product owner), Keira (front/backend), Devon (backend), Sabine (devops), Alyssa (front end)
- [x] [scrum board](https://github.com/users/sommerss/projects/2/views/1)
- [x] [backend database](https://github.com/sommerss/RobertAllen-Male-/blob/master/_notebooks/2023-05-11-reading-log-database.ipynb)
- [x] work on frontend and sorting algorithm
- [x] improve "reading log" functionality database by adding other attributes (such as pages read, author of book, date begun and then date finished, etc)
- [x] program game
- [x] leaderboard with binary search algorithm
- [x] website formatting
- [ ] connect front end (game) to backend (leaderboard)
